name: Playwright Scraper CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install

      - name: Run scraper
        run: |
          python scrape.py

      - name: Upload scraped data artifact
        uses: actions/upload-artifact@v2
        with:
          name: scraped-quotes
          path: quotes.json
